## Invite Contributors to Organization ##

inviteContributors: true


## Issue Welcome Comments ##

# Comment to send on a user's first issue in the repository.
firstIssueWelcomeComment: |
  Thank you for opening this issue. A maintainer will get by as soon as possible to address this issue.
  Since this is your first issue in this repository, please make sure follow the issue template and provide as much detail as possible.

# Comment to send on the user's forthcoming issues in the repository.
issueWelcomeComment: |
  Thank you for opening this issue. A maintainer will get by as soon as possible to address this issue.
  In the mean time, please check out our contributing guidelines to explore other ways you can get involved.


## Pull Request Welcome Comments ##

# Comment to send on a user's first pull request in the repository.
firstPullRequestWelcomeComment: |
  Welcome, apparently this is your first Pull Request in this repository, in a few moments one of the team members will 
  review it and decide what happens with it, check to have followed the template to open PRs. Thanks for collaborating

# Comment to send on the user's forthcoming pull requests in the repository.
pullRequestWelcomeComment: |
  Thank you for opening this pull request, we hope you have followed all the recommendations and the template, 
  so that our team can evaluate your contribution as soon as possible. Thanks for helping