language: node_js
node_js:
- 10.14.1
os:
- linux
sudo: required
before_install:
- sudo apt-get install dos2unix
- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
install:
- dos2unix ./test/test.sh
- dos2unix ./test/send.sh
- npm install -g eslint --save
- npm install
jobs:
  include:
  - stage: test
  - script: 
    - bash ./test/test.sh
    - fossa init
    - fossa analyze
branches:
  only:
  - master
  - deployment
  - development
  - /^dev.*$/
cache:
  directories:
  - node_modules
after_success:
- chmod +x ./test/send.sh
- "./test/send.sh success $WEBHOOK_URL"
- fossa test
after_failure:
- chmod +x ./test/send.sh
- "./test/send.sh failure $WEBHOOK_URL"