language: node_js
node_js:
- 8.12.0
os:
- linux
sudo: required
before_install:
- sudo apt-get install dos2unix
install:
- dos2unix ./travis/test.sh
- dos2unix ./travis/send.sh
- npm install -g eslint --save
- npm install
jobs:
  include:
  - stage: test
  - script: bash ./travis/test.sh
branches:
  only:
  - master
  - development
cache:
  directories:
  - node_modules
after_success:
- chmod +x ./travis/send.sh
- "./travis/send.sh success $WEBHOOK_URL"
after_failure:
- chmod +x ./travis/send.sh
- "./travis/send.sh failure $WEBHOOK_URL"
env:
  global:
    secure: FnkKBhvTxILk9aTbC8VUeMtBL03pOvzxhgv2m97GkiD+Pqz2JhsMDnCpwzZVLoL7xPh7WTd7AVp+47yeGHHVEX1MzjGlzLOP4i6Ss4mQ+3kafy8KidCdP9sYl2F3tiFONVYBCaXzLo0BzCA4hJ4248J5TTSk8eMeOV9FRNQsIYR47srTQauYGmWNB72rwPRG5JvM315TtzDT6PoitO7KQbSgJ+MDuKA2lPq1c0ZylH4JrhoADqfXdaTcgq1PT2LU0MVHZrrJCx64dM2zDLaO8uo6b2zrlqvWtDbmv0iTROb77nMHpVdQjdiftGEgtfpCoWAD3iFYOqoVNL9Y11siKs5irQxpgrR6chBVfpk4Ht97hWTmX3p7o9KLVexDw3w/JzShlzsy0VN1ik7RAyShX3wI5K9d1n00cgjliKzHKDbzby4DVK99E61Ou8xF37O6LM+JcxqhXT57V+4gKTnvSNydYDGaSJT5KM5ke8FQcfWJOAogTCdX9nriAWZOFgSY5ihblmC96l1RG6BuOodWzvD75F+OV5gHRApAUrScnejjVRQ6Ch4CzE/xb6nYeWCGQdFRGMh4RJ3LmqbH7TiUAKCABPba68pN+nyK2sheQa9ex0xahuIXiohuNSspV1EN7z7YkPiemNQL1jGlD40qa6l8rpspnFG9uX1wnpsyy0o=
deploy:
  provider: heroku
  api_key:
    secure: aEd8702qEX1EfZaKfS4Xp+jouFxVGkusqx6Zio0xv3nevL4aG1TvSMsqQnUMQebOJILCO7vGMVP6vcIwMarhXk7Jgb1Q+IwTCzOYXnMqk2mA3zlxRJ2wSW+a8Ld/AKfyv7xcEh2r1LXcIzuXT/H1w9cQRtMXlJMDkZ4k+l4pYj5mscMGtG7yv3DhFQN702ZImJSh7BUEQKHa7wCelJsnypHiEvuNY60g/nixy3NuMcVNUT6aJxiLiQkO1g03fh/b67uAMqsWBH9X8nQP+Y+VIKz0rm4hzrdK5efzdwJfqd0MqPeokpENT1m7ihzz60PLJbx6Bp4dc35Hu73eH8EvrcvRsfKGW5CHogD9YQTbklfD0TMgrl0zFoPMcXU/Nw5CMMaVscl9PUib/GlLx/gMxwpdqppH2b6ImfB7jPUJSDUTQV2iUgPS6UFpiBsjyuHPkDx2AIK/OyILxLEXS45vedLZSFSMQAkdrTMaRJqFiLNuIc4wZk9zUHtW+cN8IwclRJIF68VsuvL79V1tvS9tJR8wa/2AL/UwgnrH9R8R0J74i2Zyx/JyJWU274DTUmviraa7GaNBZKWZP7jdLGbTA69yaQoBFGgPJOu0SFZ0ZrBv+Ezy5qyfTpHapOrfOBSO5Z5uL3MdTvSbWwcvFUvyamMBb+s8ae2MbDxDYJ9Guug=
