language: node_js
node_js:
- 8.12.0
os:
- linux
sudo: required
before_install:
- sudo apt-get install dos2unix
install:
- dos2unix ./travis/test.sh
- dos2unix ./travis/send.sh
- npm install -g eslint --save
- npm install
jobs:
  include:
  - stage: test
  - script: bash ./travis/test.sh
branches:
  only:
  - master
  - development
cache:
  directories:
  - node_modules
after_success:
- chmod +x ./travis/send.sh
- "./travis/send.sh success $WEBHOOK_URL"
after_failure:
- chmod +x ./travis/send.sh
- "./travis/send.sh failure $WEBHOOK_URL"
env:
  global:
    secure: FnkKBhvTxILk9aTbC8VUeMtBL03pOvzxhgv2m97GkiD+Pqz2JhsMDnCpwzZVLoL7xPh7WTd7AVp+47yeGHHVEX1MzjGlzLOP4i6Ss4mQ+3kafy8KidCdP9sYl2F3tiFONVYBCaXzLo0BzCA4hJ4248J5TTSk8eMeOV9FRNQsIYR47srTQauYGmWNB72rwPRG5JvM315TtzDT6PoitO7KQbSgJ+MDuKA2lPq1c0ZylH4JrhoADqfXdaTcgq1PT2LU0MVHZrrJCx64dM2zDLaO8uo6b2zrlqvWtDbmv0iTROb77nMHpVdQjdiftGEgtfpCoWAD3iFYOqoVNL9Y11siKs5irQxpgrR6chBVfpk4Ht97hWTmX3p7o9KLVexDw3w/JzShlzsy0VN1ik7RAyShX3wI5K9d1n00cgjliKzHKDbzby4DVK99E61Ou8xF37O6LM+JcxqhXT57V+4gKTnvSNydYDGaSJT5KM5ke8FQcfWJOAogTCdX9nriAWZOFgSY5ihblmC96l1RG6BuOodWzvD75F+OV5gHRApAUrScnejjVRQ6Ch4CzE/xb6nYeWCGQdFRGMh4RJ3LmqbH7TiUAKCABPba68pN+nyK2sheQa9ex0xahuIXiohuNSspV1EN7z7YkPiemNQL1jGlD40qa6l8rpspnFG9uX1wnpsyy0o=
deploy:
  provider: heroku
  api_key:
    secure: qsnoLR6DJWK4FwalA3xgoma6U/+ytZK2x88RkVRLLcg4vHgNIdgEeEf+bGY97/qXz3UfOL41oah/heo39mwh1DHyWKYH+IPOX8HkEVQYlaXpnNQNHoddhvRXMZ5RJHcMrd7/R2TvpZEojziN1l1SbSma6apoaYfYEIGuYmiN0OuNcQSTm9qA5pB7T7f+tZ2TMO1/QqQ4/C49W/Kp+Y63Ei+knPJE4oyh8Xed44YjnH2FY3oaYReFAIiT+S5s/zPkxdkm+BXH2GxlBvzFZqQE8IiZeZkxq82IefLBxTcx5qvjb4igw3+AgU2GAPmabYSsA+3Q1UJN5PxoaWaijRd1p6cJmlTxVknwLHlPqxBTS7h3Z4JiFosUoII9WUq3QNceqAhMTTLw2Qignl5FCLmB4yV17b5oPNr4SPIRO+gNrZFCR7nNpAqEO62pWCnUe6Ns47ex5N7o00kaZl0D5XiBrQznkMZkk0MOqdwucQGiS1rVUdHp0iegzxL1grJboV46PToy/bdxZ7BwMZFuJtoMNDN9ZDA3jpu6Ll1khOYeTAjF163FhMcEm2n6LhZ5ROXKhJs1GMlGW7mkndRNySbF8RBEtkFrg9okIKzXJZw87Vn6vHSEwPF9XOPsC/LBKuLcb6pTWEpWyvv26e0OyUmzjbrt28c6zES0AzGi2e2htzM=
