language: node_js
node_js:
- 8.12.0
os:
- linux
sudo: required
before_install:
- sudo apt-get install dos2unix
install:
- dos2unix ./travis/test.sh
- dos2unix ./travis/send.sh
- npm install -g eslint --save
- npm install
jobs:
  include:
  - stage: test
  - script: bash ./travis/test.sh
branches:
  only:
  - master
  - development
cache:
  directories:
  - node_modules
after_success:
- chmod +x ./travis/send.sh
- "./travis/send.sh success $WEBHOOK_URL"
after_failure:
- chmod +x ./travis/send.sh
- "./travis/send.sh failure $WEBHOOK_URL"
env:
  global:
    secure: Yh0+JWLSCmkSQ+W8myjrQrY6W998gJ6BkBAz4bmdWjYmBJTL2jX2zAXequNQVgaRZJwxvkMIhs7ZbL37ESJ40kx2gE70WrJpQoE3B9ED6fyt3JfW0yZa7rHdY1/GNi2cv3iUd95lTjKTqSprPDoSyHqs9ozv6JdY1SQyutYKCzrCYYcsW8aAR7yFyDa5g0EgALCghx+ipxN7rTKlq91/tI8CP7a5nZ6saJawFeqOBFF97RQrONggKicdrZw/otccSNtdXoM9EJ/beGHFE9qBebObTftce88MgV0TNzZ7z9dbH6elNmqs6T20xps2QEeNQmslbBYmOzgUW4fhauilKj1ym5EFlXXEG+2OXpZIud9KI1XZHVgDLOqjcQcSClnPOjyXMl+kMVy49Ssh3aoHjFybOfDdc55iEXddgBWiHPsX+5f1zYMX3VEA4I6Z2txTMGnbTGaBZP6lHnKz6DP4NXmTrQIFvx0OIuJoV2TX/qW/S2ZILSh+URwwWQc0pnLEFXqcYSjcL989ElBJyQXByOgaK4lD7uPWfWbOYgPdS42VdalQuSVRJB/0rcLvWjHRHAW/XnKlsnSPzWTvzm4n7vH1sS/+u8yaB8cdZm/eqV4aiUkByEd0UF7oNbZv9g1HlyqSFVfrmeJn3GVGzRKkebvxZdM1uLtZWt0bYFvQ4dE=
